# Generated by Django 5.1.15 on 2026-03-25 06:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(
                        help_text="Incluye reglas, expectativas y detalles del club.",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Código de idioma (es, en, fr, etc.)",
                        max_length=10,
                        verbose_name="idioma",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("STRICT", "Estricto — Reporte obligatorio"),
                            ("MODERATE", "Moderado — Preguntas del creador"),
                            ("RELAXED", "Relajado — Confirmación simple"),
                            ("FREE", "Libre — Sin requisitos"),
                        ],
                        default="FREE",
                        max_length=10,
                        verbose_name="modo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("READING", "En lectura"),
                            ("SUBMISSION", "Entrega de reportes"),
                            ("REVIEW", "Revisión de reportes"),
                            ("DISCUSSION", "Debate"),
                            ("CLOSED", "Cerrado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "min_members",
                    models.PositiveIntegerField(
                        help_text="Mínimo 5 (límite de plataforma).",
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="mínimo de miembros",
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(25),
                        ],
                        verbose_name="máximo de miembros",
                    ),
                ),
                (
                    "reading_duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(7)],
                        verbose_name="días de lectura",
                    ),
                ),
                (
                    "submission_duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(3)],
                        verbose_name="días de entrega",
                    ),
                ),
                (
                    "review_duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="días de revisión",
                    ),
                ),
                (
                    "discussion_duration_days",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(3)],
                        verbose_name="días de debate",
                    ),
                ),
                (
                    "open_until",
                    models.DateTimeField(
                        help_text="Fecha límite para unirse.",
                        verbose_name="abierto hasta",
                    ),
                ),
                (
                    "reading_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio lectura"
                    ),
                ),
                (
                    "submission_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio entrega"
                    ),
                ),
                (
                    "review_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio revisión"
                    ),
                ),
                (
                    "discussion_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio debate"
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de cierre"
                    ),
                ),
                (
                    "verification_questions",
                    models.JSONField(
                        blank=True,
                        help_text='Lista de preguntas. Ej: ["¿Quién es el protagonista?", "¿Dónde ocurre?"]',
                        null=True,
                        verbose_name="preguntas de verificación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última actualización"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubs",
                        to="books.book",
                        verbose_name="libro",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "club",
                "verbose_name_plural": "clubes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CREATOR", "Creador"), ("MEMBER", "Miembro")],
                        default="MEMBER",
                        max_length=10,
                        verbose_name="rol",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de ingreso"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False si el usuario abandonó el club.",
                        verbose_name="activo",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clubs.club",
                        verbose_name="club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "club"), name="unique_membership"
                    )
                ],
            },
        ),
    ]
