# Generated by Django 5.1.15 on 2026-04-23 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "club", "is_active"], name="membership_active_idx"
            ),
        ),
    ]
