# Generated by Django 5.1.15 on 2026-03-25 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="título")),
                (
                    "author",
                    models.CharField(
                        help_text="Texto libre. En v2 será entidad separada con relación M:N.",
                        max_length=500,
                        verbose_name="autor",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="ISBN"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, default="", verbose_name="portada URL"),
                ),
                (
                    "google_books_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Google Books ID",
                    ),
                ),
                (
                    "is_manual_entry",
                    models.BooleanField(
                        default=False,
                        help_text="True si el usuario lo registró manualmente (no está en Google Books).",
                        verbose_name="registro manual",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de registro"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "libro",
                "verbose_name_plural": "libros",
                "ordering": ["title"],
            },
        ),
    ]
