# Generated by Django 5.1.15 on 2026-03-25 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Reporte"),
                            ("COMMENT", "Comentario"),
                            ("DISCUSSION_TOPIC", "Tema de debate"),
                        ],
                        max_length=20,
                        verbose_name="tipo de contenido",
                    ),
                ),
                (
                    "content_id",
                    models.PositiveIntegerField(
                        help_text="ID del reporte, comentario o tema reportado.",
                        verbose_name="ID del contenido",
                    ),
                ),
                ("reason", models.TextField(verbose_name="motivo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="resuelto"),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reportado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "flag de contenido",
                "verbose_name_plural": "flags de contenido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscussionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="tema propuesto")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_topics",
                        to="clubs.club",
                        verbose_name="club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propuesto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "tema de debate",
                "verbose_name_plural": "temas de debate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="reflexión")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de entrega"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        default=False,
                        help_text="True si se entregó fuera del periodo de SUBMISSION.",
                        verbose_name="entrega tardía",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="clubs.club",
                        verbose_name="club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte",
                "verbose_name_plural": "reportes",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LIKE", "Me gusta"),
                            ("INTERESTING", "Interesante"),
                            ("AGREE", "De acuerdo"),
                            ("DISAGREE", "En desacuerdo"),
                        ],
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="reports.report",
                        verbose_name="reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "reacción",
                "verbose_name_plural": "reacciones",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reports.report",
                        verbose_name="reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "comentario",
                "verbose_name_plural": "comentarios",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        help_text="JSON con las respuestas a cada pregunta.",
                        verbose_name="respuestas",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False,
                        help_text="Si el moderador aprobó las respuestas.",
                        verbose_name="aprobado",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de envío"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_answers",
                        to="clubs.club",
                        verbose_name="club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "respuesta de verificación",
                "verbose_name_plural": "respuestas de verificación",
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("user", "club"), name="unique_report_per_user_per_club"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("user", "report", "type"), name="unique_reaction_per_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationanswer",
            constraint=models.UniqueConstraint(
                fields=("user", "club"), name="unique_verification_per_user_per_club"
            ),
        ),
    ]
